"""Initial migration

Revision ID: 99818e957aa3
Revises:
Create Date: 2017-12-31 19:34:00.865223+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99818e957aa3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reported_events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('recorder', sa.String(), nullable=True),
                    sa.Column('what', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('earliest', sa.DateTime(), nullable=True),
                    sa.Column('latest', sa.DateTime(), nullable=True),
                    sa.Column('estimated_start', sa.DateTime(), nullable=True),
                    sa.Column('estimated_end', sa.DateTime(), nullable=True),
                    sa.Column('location_description', sa.String(),
                              nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('location_error_in_meters', sa.Float(),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reported_events')
    # ### end Alembic commands ###
